services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - ./node_modules:/app/node_modules
    command: ["yarn", "dev"]
    environment:
      NODE_ENV: development

  build:
    build:
      context: .
      dockerfile: Dockerfile
    command: [ "yarn", "build" ]
    volumes:
      - .:/app
      - ./node_modules:/app/node_modules
    environment:
      NODE_ENV: production
      EXPORT: export
      BASE_PATH: ''
      UNOPTIMIZED: true

  install:
    build:
      context: .
      dockerfile: Dockerfile
    command: [ "yarn", "install" ]
    volumes:
      - .:/app
      - ./node_modules:/app/node_modules
